const RECIPES = [
  {
    id: 1,
    title: "Clam Chowder",
    contributor: "Lorna",
    category: "Main Dish",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 large", item: "onion (chopped)" },
      { amount: "1 c", item: "celery (chopped)" },
      { amount: "1 c", item: "diced carrots" },
      { amount: "2 c", item: "potatoes" },
      { amount: "3 tbsp", item: "butter" },
      { amount: "½ tsp", item: "salt" },
      { amount: "½ tsp", item: "pepper or to taste" },
      { amount: "3 tins (4½ oz)", item: "minced clams" },
      { amount: "1 tin (5½ oz approx)", item: "shrimp" },
      { amount: "½–1 lbs", item: "bacon (fried & diced)" },
      { amount: "2 qts", item: "milk (more or less)" },
      { amount: "1/3 c", item: "flour" },
    ],
    steps: [
      "Cook vegetables, seasonings and butter (in large pot) covered with water.",
      "When veg. are cooked, add bacon, then milk. Heat thoroughly (along with clam juice) and thicken with flour dissolved in milk.",
      "Once thickened, reduce heat and add the clams and shrimp.",
      "DO NOT BOIL AGAIN as seafood will toughen.",
    ],
    notes: null,
  },
  {
    id: 2,
    title: "Kentucky Burgoo",
    contributor: "Karen",
    category: "Main Dish",
    servings: 12,
    temps: "Simmer 3 hrs.",
    ingredients: [
      { amount: "2 lbs", item: "round steak (1½\" cubes)" },
      { amount: "one 3 lb", item: "chicken" },
      { amount: "1 tsp", item: "tabasco sauce" },
      { amount: "3 tsp", item: "salt (divided)" },
      { amount: "11 c", item: "water" },
      { amount: "2 c", item: "pared diced potatoes" },
      { amount: "2 c", item: "chopped onions" },
      { amount: "1 clove", item: "garlic minced" },
      { amount: "2 c", item: "pared diced carrots" },
      { amount: "one 28 oz can", item: "tomatoes" },
      { amount: "one 8 oz can", item: "tomato sauce" },
      { amount: "5", item: "beef bouillon cubes" },
      { amount: "one 10 oz pkg", item: "frozen cut green beans" },
      { amount: "two 10 oz pkgs", item: "frozen kernel corn" },
      { amount: "two 10 oz pkgs", item: "frozen peas" },
    ],
    steps: [
      "In very large kettle combine beef cubes, whole chicken, tabasco sauce, 1 tsp salt and water. Cover, bring to boil, reduce heat and simmer, covered, 1½ hours.",
      "Remove chicken from pot and set aside to cool.",
      "Add the 2 tsp salt and all other remaining ingredients to pot. Cover and simmer 1½ hours.",
      "Meanwhile, remove skin from chicken and pull meat from bones. Cut into bite sized pieces. Add chicken to beef mixture and heat through. Discard skin and bones.",
    ],
    notes: "SERVES TWELVE.",
  },
  {
    id: 3,
    title: "Maritimer's Clam Chowder",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "Simmer approx. ½ hour",
    ingredients: [
      { amount: "6 medium", item: "potatoes" },
      { amount: "1 large", item: "onion" },
      { amount: "2 tbsp", item: "margarine" },
      { amount: "3 c", item: "milk" },
      { amount: "1 can", item: "kernel corn & juice" },
      { amount: "2 cans", item: "baby clams & juice" },
      { amount: "½ tsp", item: "paprika" },
      { amount: "to taste", item: "salt & pepper" },
    ],
    steps: [
      "Peel and cube potatoes. Chop onions. Place in a saucepan cover with water, add salt, and boil for approximately 15 minutes (just until the potatoes are partially cooked). Drain off the water.",
      "Place the potatoes and onions back in the saucepan and add corn & juice, clams & juice then the milk and margarine. Use your own judgement as to the amount of milk you add — using just enough to cover the ingredients if you like it like a stew or add more milk if you like it like a soup. Add the paprika and salt and pepper to taste.",
      "Simmer for about ½ an hour or until the potatoes are cooked.",
    ],
    notes: null,
  },
  {
    id: 4,
    title: "Sweet and Sour Meatballs",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "225° for 2½ hours OR Slow cooker 8 hours",
    ingredients: [
      { amount: "1½ lb", item: "hamburger" },
      { amount: "1 pkge", item: "dry onion soup" },
      { amount: "1", item: "egg (beaten)" },
      { amount: "6", item: "soda crackers (crushed fine)" },
      { amount: "1 c", item: "grape jelly" },
      { amount: "1 c", item: "chili sauce (bottled)" },
    ],
    steps: [
      "Combine hamburger, onion soup, egg and cracker crumbs mixing thoroughly with your hands. Make small meatballs and brown both sides. Drain the meatballs and place in a roasting pan or slow cooker.",
      "In a saucepan, heat the grape jelly and chili sauce until melted together. Pour over the meatballs and bake or slow cook.",
    ],
    notes: "THE CHILI SAUCE IS PURCHASED IN YOUR LOCAL GROCERY STORE IN THE SECTION WHERE YOU WOULD BUY KETCHUP.",
  },
  {
    id: 5,
    title: "Breasts of Chicken",
    contributor: "Corinne",
    category: "Main Dish",
    servings: 6,
    temps: "375° for 1 hour",
    ingredients: [
      { amount: "6", item: "chicken breasts (boneless)" },
      { amount: "to taste", item: "salt & pepper" },
      { amount: "½ tsp", item: "basil" },
      { amount: "1 c", item: "flour" },
      { amount: "1 c", item: "milk" },
      { amount: "1 c", item: "parmesan cheese, grated" },
      { amount: "1½ c", item: "fine ground white bread crumbs" },
      { amount: "1 tsp", item: "parsley, chopped" },
      { amount: "1 clove", item: "garlic minced" },
      { amount: "1 c", item: "butter" },
      { amount: "½ c", item: "oil" },
    ],
    steps: [
      "Season breasts with salt, pepper and basil.",
      "Coat with flour and dip in milk.",
      "Bread with cheese, bread crumbs & parsley combined.",
      "Repeat dip and breading.",
      "Sauté garlic in butter and oil.",
      "Add breasts and sauté until golden. Bake.",
    ],
    notes: null,
  },
  {
    id: 6,
    title: "Chicken Balls",
    contributor: "Phyllis",
    category: "Main Dish",
    servings: null,
    temps: "250° for 1 hour",
    ingredients: [
      { amount: "2–3", item: "chicken breasts" },
      { amount: "1 or 2", item: "eggs (beaten)" },
      { amount: "½ c", item: "flour" },
      { amount: "1 tsp", item: "accent" },
      { amount: "1 tsp", item: "salt" },
    ],
    steps: [
      "To prepare chicken, mix flour, accent, salt. Cut chicken into bite size pieces. Roll chicken pieces in egg, dip in flour mixture and fry in oil until light brown.",
      "To prepare sauce, combine all sauce ingredients EXCEPT cornstarch, and bring to a boil, thickening with cornstarch. Pour over chicken balls and bake.",
    ],
    notes: "Sauce: ½ c sugar, ½ c vinegar, 1 tbsp soya sauce, ½ c pineapple chunks, 1/3 c pineapple juice, ¼ c catsup, sprinkle of pepper, 2 tbsp cornstarch.",
  },
  {
    id: 7,
    title: "Chinese Chicken Wings",
    contributor: "Kim",
    category: "Main Dish",
    servings: null,
    temps: "375° for 1 hour",
    ingredients: [
      { amount: "3 lbs", item: "chicken wings" },
      { amount: "to taste", item: "salt & pepper" },
      { amount: "2 tbsp", item: "vegetable oil" },
      { amount: "1 c", item: "honey" },
      { amount: "½ c", item: "soya sauce" },
      { amount: "1 clove", item: "garlic – mashed" },
      { amount: "2 tbsp", item: "ketchup" },
    ],
    steps: [
      "Cut off and discard tips from chicken wings. Cut remaining wings into 2 parts. Sprinkle with salt, pepper and oil.",
      "Combine remaining ingredients and pour over wings.",
      "Bake in shallow 10\" X 15\" pan for one hour or more, basting often.",
    ],
    notes: null,
  },
  {
    id: 8,
    title: "B-B-Q Spareribs",
    contributor: "Fleurette",
    category: "Main Dish",
    servings: null,
    temps: "On the B-B-Q",
    ingredients: [
      { amount: "1 c", item: "ketchup" },
      { amount: "¼ c", item: "water" },
      { amount: "¼ c", item: "lemon juice" },
      { amount: "¼ c", item: "honey or brown sugar" },
      { amount: "3 tbsp", item: "Worcestershire sauce" },
      { amount: "2 tsp", item: "prepared mustard" },
      { amount: "1 tsp", item: "garlic powder" },
      { amount: "1 tsp", item: "salt" },
      { amount: "¼ tsp", item: "thyme" },
    ],
    steps: [
      "Combine all sauce ingredients and simmer 5 minutes.",
      "Cook spareribs flat, rotate them in a split basket, or thread them in and out like an accordion on an oiled spit skewer.",
      "Cook ribs slowly until the meat shrinks away from the ends of the bones. Baste regularly during cooking.",
    ],
    notes: null,
  },
  {
    id: 9,
    title: "Company Chicken",
    contributor: "Shirley",
    category: "Main Dish",
    servings: null,
    temps: "350° for 1 hour",
    ingredients: [
      { amount: "to taste", item: "chicken pieces" },
      { amount: "to taste", item: "flour" },
      { amount: "½ tsp", item: "curry powder" },
      { amount: "1 can", item: "cream of chicken or mushroom soup" },
      { amount: "1 can", item: "mushrooms with the liquid" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Roll chicken in flour and brown in skillet.",
      "Place chicken in casserole dish.",
      "Add soup, mushrooms with liquid, salt, pepper, curry powder to the fry pan the chicken was in. Simmer for a few minutes and pour this over the chicken. Bake.",
      "The above makes gravy for mashed potatoes.",
    ],
    notes: null,
  },
  {
    id: 10,
    title: "Sweet and Sour Pork",
    contributor: "Fran",
    category: "Main Dish",
    servings: null,
    temps: "Pan fry – 45 minutes",
    ingredients: [
      { amount: "2 lbs", item: "lean boneless pork" },
      { amount: "2 tbsp", item: "vegetable oil" },
      { amount: "1 clove", item: "garlic, chopped" },
      { amount: "to taste", item: "salt and pepper" },
      { amount: "19 oz can", item: "pineapple chunks (keep the juice)" },
      { amount: "2 tbsp", item: "cornstarch" },
      { amount: "¼ c", item: "brown sugar" },
      { amount: "½ c", item: "water" },
      { amount: "½ c", item: "wine vinegar" },
      { amount: "1 tbsp", item: "soya sauce" },
      { amount: "1", item: "green pepper (cut in 1\" pieces)" },
      { amount: "½ c", item: "maraschino cherries" },
    ],
    steps: [
      "Cut pork into 1\" cubes.",
      "Heat oil in electric frying pan.",
      "Sauté garlic then meat cubes. Salt and pepper meat.",
      "In a small saucepan, combine cornstarch, water and brown sugar (add pineapple juice too) and simmer until it thickens to form a sauce.",
      "Pour over meat and simmer 30 minutes or until meat is tender. (It may be necessary to add additional water.)",
      "Add pineapple chunks, cherries and green pepper. Cook another 10 minutes.",
      "Serve with plain rice.",
    ],
    notes: null,
  },
  {
    id: 11,
    title: "Meat Loaf",
    contributor: "Melba",
    category: "Main Dish",
    servings: null,
    temps: "350° for 1 hour",
    ingredients: [
      { amount: "2 lbs", item: "hamburger" },
      { amount: "½–1 c", item: "soft bread crumbs" },
      { amount: "3/4 c", item: "warm water" },
      { amount: "1/3 c", item: "ketchup" },
      { amount: "1 pkge", item: "dry onion soup mix" },
      { amount: "2", item: "eggs slightly beaten" },
    ],
    steps: [
      "Mix water, ketchup, soup mix and eggs.",
      "Mix bread crumbs and hamburger and add the above mixture. Mix by hand until combined. Bake.",
    ],
    notes: null,
  },
  {
    id: 12,
    title: "Chinese Food",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "Pan fry – 30 minutes",
    ingredients: [
      { amount: "1 c", item: "diced roast beef OR pork OR chicken" },
      { amount: "1 c", item: "sliced carrots" },
      { amount: "1 c", item: "sliced onions" },
      { amount: "1 can", item: "whole mushrooms" },
      { amount: "2 tbsp", item: "soya sauce" },
      { amount: "1 tbsp", item: "white sugar" },
      { amount: "to taste", item: "salt" },
      { amount: "1 tbsp", item: "cornstarch mixed with a little cold water" },
      { amount: "1 c", item: "sliced celery" },
      { amount: "1 c", item: "green peas (frozen)" },
      { amount: "1", item: "green pepper sliced (optional)" },
      { amount: "1 c", item: "slivered almonds (use with chicken)" },
    ],
    steps: [
      "Fry meat in a tbsp oil over hot fire, turning constantly until brown.",
      "Add 1 tbsp soya sauce, stir, remove from pan, put aside.",
      "Cook carrots, celery and mushrooms, adding just enough water to prevent burning, turning the vegetables. Vegetables for Chinese food should not be over cooked.",
      "Add onions, green peas and peppers towards the last.",
      "Add a tbsp sugar, 1 tbsp soya sauce and salt to taste.",
      "Thicken with cornstarch-water mixture. Mix in meat and sprinkle with almonds for chicken chop suey.",
      "Serve with rice.",
    ],
    notes: null,
  },
  {
    id: 13,
    title: "Hot Curried Fruit",
    contributor: "Shirley",
    category: "Main Dish",
    servings: null,
    temps: "300° for 20–25 min.",
    ingredients: [
      { amount: "1 c", item: "brown sugar" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "1 tbsp", item: "curry" },
      { amount: "½ c", item: "butter" },
      { amount: "3 – 14 oz cans", item: "drained fruit (pineapple, pears, peaches, apricots, or mandarin oranges; maraschino cherries for color)" },
    ],
    steps: [
      "Combine first four ingredients in a saucepan and bring to a boil. Cook 5 minutes.",
      "Pour over fruit in a buttered casserole dish. Bake.",
    ],
    notes: null,
  },
  {
    id: 14,
    title: "Quick Quiche",
    contributor: "Fran",
    category: "Main Dish",
    servings: null,
    temps: "400° for 35 minutes",
    ingredients: [
      { amount: "1", item: "frozen pie shell" },
      { amount: "2/3 c", item: "half & half cream" },
      { amount: "3", item: "eggs" },
      { amount: "2/3 c", item: "grated Swiss Cheese" },
      { amount: "to taste", item: "salt and pepper" },
      { amount: "3 slices", item: "bacon chopped" },
      { amount: "1 c", item: "raw spinach shredded in small pieces" },
      { amount: "2 tbsp", item: "minced green onions" },
      { amount: "¼ c", item: "sliced mushrooms" },
    ],
    steps: [
      "While preparing filling, bake pie shell for 8 to 10 minutes.",
      "Sauté bacon, mushrooms, spinach and onions.",
      "In a medium size bowl, beat the eggs, add the cream, cheese, salt and pepper.",
      "To the cheese mixture add sautéed bacon mixture.",
      "Pour into partially baked shell and bake. Quiche is baked when metal knife comes out clean.",
    ],
    notes: "VARIATIONS – Use 1 large can of either shrimp, crab or salmon.\n\nThis recipe is excellent for brunch. Serve with a fresh fruit cocktail for an appetizer. Accompany with a spinach and mushroom salad and hot rolls.",
  },
  {
    id: 15,
    title: "Lasagna",
    contributor: "Beryl",
    category: "Main Dish",
    servings: null,
    temps: "325° for 1 hour",
    ingredients: [
      { amount: "1 lb", item: "ground pork" },
      { amount: "1 lb", item: "ground beef" },
      { amount: "2 large", item: "onions chopped" },
      { amount: "10 oz can", item: "tomato soup" },
      { amount: "8 oz can", item: "tomato paste" },
      { amount: "20 oz can", item: "whole tomatoes" },
      { amount: "2 – 14 oz cans", item: "Italian tomato sauce" },
      { amount: "½ c", item: "sugar" },
      { amount: "3 tbsp", item: "parsley" },
      { amount: "16 oz pkge", item: "mozz. cheese slices" },
      { amount: "12 oz pkge", item: "swiss cheese slices" },
      { amount: "5 shakes", item: "Worcestershire sauce" },
      { amount: "½ tsp", item: "oregano" },
      { amount: "½ tsp", item: "poultry seasoning" },
      { amount: "½ tsp", item: "sage" },
      { amount: "¼ tsp", item: "nutmeg" },
      { amount: "½ tsp", item: "thyme" },
      { amount: "½ tsp", item: "salt" },
      { amount: "¼ tsp", item: "pepper" },
      { amount: "2 cloves", item: "garlic, crushed" },
      { amount: "to taste", item: "parmesan cheese" },
    ],
    steps: [
      "Brown pork and beef. Drain off fat.",
      "Boil the onions until transparent and drain off water.",
      "Combine remaining ingredients with the meat and onions EXCEPT cheese and simmer for 2 hours.",
      "Cook enough lasagna noodles to layer in an 8 X 8 AND 9 X 11 pan.",
      "In the pans layer noodles, meat, cheese – noodles, meat, cheese. (Cheeses should be checker board style.) Sprinkle parmesan cheese on top of last layer. Bake.",
      "Once the lasagna is baked LET STAND 15 minutes before serving.",
    ],
    notes: "Checker board style means alternating swiss and mozzarella slices in a grid pattern.",
  },
  {
    id: 16,
    title: "Tuna Casserole",
    contributor: "Melba",
    category: "Main Dish",
    servings: 6,
    temps: "425° for 20 minutes",
    ingredients: [
      { amount: "6½ oz can", item: "tuna, drained" },
      { amount: "½ c", item: "mayonnaise" },
      { amount: "1 c", item: "sliced celery" },
      { amount: "1/3 c", item: "chopped onion" },
      { amount: "¼ c", item: "canned pimento" },
      { amount: "6 oz pkge (3 cups)", item: "medium noodles, cooked & drained" },
      { amount: "½ tsp", item: "salt" },
      { amount: "10½ oz can", item: "cream of mushroom soup" },
      { amount: "½ c", item: "milk" },
      { amount: "4 oz", item: "sharp cheese (shredded – 1 c)" },
      { amount: "½ c", item: "slivered almonds (optional)" },
    ],
    steps: [
      "Combine soup and milk and heat through. Add shredded cheese and heat until cheese melts.",
      "In a bowl, combine remaining ingredients EXCEPT almonds, then mix in the soup mixture. If desired, top with almonds and bake in a 2 quart casserole dish (ungreased & uncovered).",
    ],
    notes: null,
  },
  {
    id: 17,
    title: "Left Over Chicken Casserole",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "300° for 45 minutes",
    ingredients: [
      { amount: "1½ c", item: "cut up left over chicken" },
      { amount: "1 can", item: "cream of mushroom soup" },
      { amount: "2 c", item: "sliced carrots" },
      { amount: "¼ c", item: "diced onions" },
      { amount: "½ c", item: "diced celery" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Cook carrots, celery and onion in water until carrots are done. DO NOT THROW OUT CARROT WATER.",
      "Combine soup and carrot water in casserole dish, mixing until creamy. Add remaining ingredients and bake.",
      "You can serve this with rice or top with Tea Biscuits the last 10–15 minutes in the oven.",
    ],
    notes: null,
  },
  {
    id: 18,
    title: "Steak Casserole",
    contributor: "Gail",
    category: "Main Dish",
    servings: null,
    temps: "250° for 3 hours",
    ingredients: [
      { amount: "1½ lbs", item: "round steak (cut in narrow strips)" },
      { amount: "1 can", item: "cream of mushroom soup" },
      { amount: "1 c", item: "half & half cream" },
    ],
    steps: [
      "Brown meat strips on high heat in fry pan using salt and pepper to taste. Remove meat and add a little water and simmer for 5 minutes.",
      "In a casserole dish mix mushroom soup and cream, add meat and water mixture. Bake.",
    ],
    notes: null,
  },
  {
    id: 19,
    title: "Seafood Casserole",
    contributor: "Melba",
    category: "Main Dish",
    servings: 6,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "2 cans", item: "large or medium shrimp" },
      { amount: "1 can", item: "lobster" },
      { amount: "1 can", item: "crab meat" },
      { amount: "1/3 c", item: "butter" },
      { amount: "1 can", item: "whole mushrooms" },
      { amount: "¼ c", item: "chopped onions" },
      { amount: "1/3 c", item: "flour" },
      { amount: "½ tsp", item: "salt" },
      { amount: "3/4 c", item: "milk" },
      { amount: "½ pint", item: "light cream" },
      { amount: "2 tbsp", item: "sherry" },
      { amount: "1 c", item: "crushed rice crispies" },
      { amount: "2 tbsp", item: "melted butter" },
    ],
    steps: [
      "Drain seafood and break up lobster and crab meat.",
      "Melt 1/3 c butter, add mushrooms and onions, sauté. Add flour then cream, milk and sherry. Boil.",
      "Add seafood to above mixture and pour into casserole dish.",
      "Melt 2 tbsp butter and add crushed rice crispies. Spread on top of casserole. Bake.",
    ],
    notes: null,
  },
  {
    id: 20,
    title: "Honey and Garlic Ribs",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "350° for 1 hour",
    ingredients: [
      { amount: "2 lbs", item: "lean pork ribs" },
      { amount: "4 tbsp", item: "oil" },
      { amount: "2 tsp", item: "ginger" },
      { amount: "1 tsp", item: "garlic" },
      { amount: "5 tbsp", item: "liquid honey" },
    ],
    steps: [
      "Cut ribs into individual pieces. Boil in water for about 20 minutes and drain.",
      "Mix oil, ginger and garlic. Brown ribs in fry pan with the aforementioned mixture.",
      "Place in casserole dish and bake. ADD the honey the last ½ hour and mix thoroughly.",
    ],
    notes: null,
  },
  {
    id: 21,
    title: "Seafood Casserole",
    contributor: "Karen",
    category: "Main Dish",
    servings: null,
    temps: "325° for 45 minutes",
    ingredients: [
      { amount: "2 c", item: "chopped onion" },
      { amount: "3 c", item: "chopped celery" },
      { amount: "3 tbsp", item: "butter" },
      { amount: "1 tsp", item: "salt" },
      { amount: "¼ tsp", item: "pepper" },
      { amount: "5 c", item: "milk" },
      { amount: "3/4 c", item: "flour" },
      { amount: "½ c", item: "butter" },
      { amount: "1 lb", item: "sliced pasteurized cheese" },
      { amount: "10 ounces", item: "lobster meat" },
      { amount: "3/4 lb", item: "cooked shrimp" },
      { amount: "1 lb", item: "cooked scallops, quartered" },
      { amount: "½ lb", item: "crabmeat" },
    ],
    steps: [
      "Sauté onion and celery in 3 tbsp butter, add salt and pepper. Set aside.",
      "Bring milk to boil, mix in butter and flour. Add sautéed celery and onions – add cheese slices. Cook until cheese is melted and sauce is slightly thickened.",
      "Add seafoods and place in large casserole dish. Bake until bubbly and brown (approx. 45 minutes).",
    ],
    notes: "This is good added over baked potatoes.",
  },
  {
    id: 22,
    title: "Chili",
    contributor: "Melba",
    category: "Main Dish",
    servings: null,
    temps: "Simmer 1½–2 hours",
    ingredients: [
      { amount: "1 lb", item: "hamburger" },
      { amount: "½ c", item: "chopped onion" },
      { amount: "1 can", item: "tomato soup" },
      { amount: "1 can", item: "kidney beans" },
      { amount: "1 tbsp", item: "vinegar" },
      { amount: "1½ tsp", item: "chili powder" },
    ],
    steps: [
      "Brown hamburger and onions. Drain off excess fat.",
      "Add remaining ingredients and simmer.",
    ],
    notes: null,
  },
  {
    id: 23,
    title: "Shirley's Cheaper Cut Roast",
    contributor: "Shirley",
    category: "Main Dish",
    servings: null,
    temps: "450° for 2 hours, then 325° for 2–3 hours",
    ingredients: [
      { amount: "4–5 lb", item: "cheap cut roast (chuck roast works well)" },
    ],
    steps: [
      "Place roast in pan, salt and pepper to taste. DO NOT ADD WATER. Place lid on top and bake one hour, turn the roast over and bake another hour with the lid on.",
      "Turn the oven down and continue baking. You may need to add a little water near the end, but add just a small amount.",
    ],
    notes: "May add potatoes and carrots last hour.",
  },
  {
    id: 24,
    title: "Roasting a Chicken",
    contributor: "Karen",
    category: "Main Dish",
    servings: 6,
    temps: "425° for 1 hr, then 350° for 1½ hrs",
    ingredients: [
      { amount: "5–6 lb", item: "chicken or turkey" },
      { amount: "to taste", item: "melted butter or margarine" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Place chicken or turkey in roasting pan. Brush with melted butter and season with salt and pepper to taste. Bake at 425° for about an hour (enough to brown it). MAKE SURE THE LID IS OFF and DON'T ADD WATER.",
      "Pour a LITTLE hot water, put the lid on and continue baking at 350° for approximately 1½ hours.",
      "If you have a larger chicken or turkey, just increase the times.",
    ],
    notes: "IT IS NOT NECESSARY TO BASTE YOUR CHICKEN OR TURKEY.\n\nWhen preparing your dressing, use MILK instead of water for more taste.",
  },
  {
    id: 25,
    title: "Asparagus with Cheese",
    contributor: "Corinne",
    category: "Side Dish",
    servings: 4,
    temps: "350° for 5 minutes",
    ingredients: [
      { amount: "1 lb", item: "fresh asparagus, or one 10 oz pkg frozen" },
      { amount: "½ c", item: "shredded swiss cheese" },
      { amount: "2 tbsp", item: "chopped canned pimiento" },
      { amount: "2 tsp", item: "sesame seed, toasted" },
    ],
    steps: [
      "In a 10\" skillet, cook asparagus spears in salted, boiling water until tender. Drain.",
      "Toss together the cheese, pimiento, and sesame seed.",
      "Place asparagus in baking dish and sprinkle with cheese mixture. Bake at 350° until cheese is melted, about 5 minutes.",
    ],
    notes: "Serves 4.",
  },
  {
    id: 26,
    title: "Potatoes for Ten",
    contributor: "Beryl",
    category: "Side Dish",
    servings: 10,
    temps: "350° for 1–1½ hours",
    ingredients: [
      { amount: "2 lbs", item: "hash browns" },
      { amount: "2 cans", item: "mushroom soup" },
      { amount: "1", item: "chopped onion" },
      { amount: "½ c", item: "melted butter" },
      { amount: "2 c", item: "grated cheddar cheese" },
      { amount: "to taste", item: "parmesan cheese (in the can)" },
    ],
    steps: [
      "Mix all ingredients EXCEPT parmesan cheese. Sprinkle the parmesan cheese on top and bake in uncovered casserole.",
    ],
    notes: null,
  },
  {
    id: 27,
    title: "Baked Broccoli Casserole",
    contributor: "Cally",
    category: "Side Dish",
    servings: 8,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "2 bunches", item: "fresh broccoli" },
      { amount: "3 stalks", item: "diced celery" },
      { amount: "1 can", item: "mushrooms" },
      { amount: "2 medium", item: "onions – chopped" },
      { amount: "1½ c", item: "sharp cheddar cheese – grated" },
      { amount: "½ c", item: "buttered bread crumbs" },
      { amount: "2 tbsp", item: "flour" },
      { amount: "1 large tin", item: "mushroom soup" },
    ],
    steps: [
      "Skin the stems of the broccoli. Chop all the broccoli including the flowerettes. Steam for a few minutes until only slightly done but still crisp. Drain.",
      "Sauté celery, mushrooms and onion in butter. Set aside.",
      "Heat soup in saucepan, add flour and stir until smooth, then add grated cheese.",
      "Combine vegetables with soup mixture and pour into buttered casserole dish (1½ qt).",
      "Cover with crumbs and bake.",
    ],
    notes: null,
  },
  {
    id: 28,
    title: "Corn Casserole",
    contributor: "Beryl",
    category: "Side Dish",
    servings: null,
    temps: "350° for 40 minutes",
    ingredients: [
      { amount: "1 – 20 oz can", item: "cream corn" },
      { amount: "1 c", item: "evaporated milk" },
      { amount: "1 tbsp", item: "butter" },
      { amount: "3/4 c", item: "cracker crumbs" },
      { amount: "3", item: "hard boiled eggs (chopped)" },
      { amount: "2 tbsp", item: "finely chopped onion" },
      { amount: "¼ tsp", item: "celery salt" },
      { amount: "¼ tsp", item: "salt and pepper" },
      { amount: "1/3 c", item: "cracker crumbs (for topping)" },
    ],
    steps: [
      "Heat milk and butter. Combine with remaining ingredients EXCEPT 1/3 c cracker crumbs.",
      "Pour into buttered casserole dish and sprinkle with 1/3 cup of cracker crumbs. Dot with butter and bake.",
    ],
    notes: null,
  },
  {
    id: 29,
    title: "Turnip Casserole",
    contributor: "Melba",
    category: "Side Dish",
    servings: 6,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "2 c", item: "mashed cooked turnip" },
      { amount: "3 tbsp", item: "margarine" },
      { amount: "1 tbsp", item: "sugar" },
      { amount: "1 tsp", item: "salt" },
      { amount: "dash", item: "pepper" },
      { amount: "1 c", item: "soft bread crumbs" },
      { amount: "2", item: "eggs (beaten)" },
      { amount: "1 tbsp", item: "butter (melted)" },
    ],
    steps: [
      "Combine turnip, 3 tbsp marg., sugar, salt and pepper, 3/4 c crumbs, eggs. Mix well and turn into buttered 1 quart casserole dish.",
      "Mix remaining crumbs and melted butter. Sprinkle on top. Bake.",
    ],
    notes: null,
  },
  {
    id: 30,
    title: "Tuna Salad",
    contributor: "Lorna",
    category: "Salad",
    servings: null,
    temps: "Refrigerate",
    ingredients: [
      { amount: "1 can", item: "tuna" },
      { amount: "1 can", item: "chicken gumbo soup" },
      { amount: "2–3 tbsp", item: "chopped green onion" },
      { amount: "2 tbsp", item: "chopped celery" },
      { amount: "1 c", item: "mayonnaise" },
      { amount: "½ c", item: "whipping cream" },
      { amount: "1 small", item: "Lemon jello" },
      { amount: "1 c", item: "boiling water" },
    ],
    steps: [
      "Partially set jelly and stir in rest of ingredients. Part of cream may be omitted for firmer salad.",
      "When doubled, you might add 1 tbsp plain gelatin.",
      "This salad may be placed in individual molds, if desired.",
    ],
    notes: null,
  },
  {
    id: 31,
    title: "Spinach Salad",
    contributor: "Kim",
    category: "Salad",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "to taste", item: "spinach leaves" },
      { amount: "3 slices", item: "crumbled bacon" },
      { amount: "1 c", item: "shredded hard boiled egg" },
      { amount: "to taste", item: "mushrooms (optional)" },
      { amount: "to taste", item: "red onion (optional)" },
      { amount: "1", item: "egg yolk" },
      { amount: "½ tsp", item: "seasoned salt" },
      { amount: "½ tsp", item: "dry mustard" },
      { amount: "4 heaping tsp", item: "sour cream" },
      { amount: "1–2 tsp", item: "Tarragon vinegar" },
      { amount: "½ c", item: "olive oil" },
      { amount: "to taste", item: "garlic" },
    ],
    steps: [
      "Combine salad ingredients in order given and toss.",
      "Combine dressing ingredients in order, mixing well after each. Pour over salad and toss until evenly coated.",
    ],
    notes: null,
  },
  {
    id: 32,
    title: "Macaroni Salad",
    contributor: "Marc",
    category: "Salad",
    servings: 6,
    temps: null,
    ingredients: [
      { amount: "3 c", item: "macaroni bows" },
      { amount: "6", item: "hard cooked eggs (chopped)" },
      { amount: "½ c", item: "cubed cheddar cheese" },
      { amount: "1 c", item: "thinly sliced celery" },
      { amount: "1 oz", item: "finely chopped green onion" },
      { amount: "2/3 c", item: "mayonnaise" },
      { amount: "½ tsp", item: "dried mustard" },
      { amount: "½ tsp", item: "salt" },
      { amount: "to taste", item: "lettuce leaves" },
    ],
    steps: [
      "Cook macaroni, drain and rinse with cold water.",
      "Combine eggs, cheese, celery, mayonnaise, onions, mustard and salt. Stir in macaroni.",
      "Chill if time permits for better results.",
    ],
    notes: null,
  },
  {
    id: 33,
    title: "Fruit Salad",
    contributor: "Lorna",
    category: "Salad",
    servings: null,
    temps: "Chill",
    ingredients: [
      { amount: "1 c", item: "drained pineapple chunks" },
      { amount: "1 c", item: "drained canned mandarin oranges" },
      { amount: "1 c", item: "coconut" },
      { amount: "1 c", item: "sour cream" },
      { amount: "2/3 bag", item: "Kraft miniature colored marshmallows" },
    ],
    steps: [
      "Mix and completely chill before serving.",
    ],
    notes: null,
  },
  {
    id: 34,
    title: "Cottage Cheese Salad",
    contributor: "Fran",
    category: "Salad",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 pkge.", item: "lime jello" },
      { amount: "1 c", item: "hot water" },
      { amount: "18", item: "marshmallows (cut up)" },
      { amount: "1 lb", item: "cottage cheese" },
      { amount: "1 can", item: "crushed pineapple" },
      { amount: "1 c", item: "salad dressing" },
      { amount: "1 tsp", item: "lemon juice" },
    ],
    steps: [
      "Combine lime jello and hot water.",
      "Add marshmallows. Let cool and add cottage cheese.",
      "Add remaining ingredients and toss all together.",
    ],
    notes: null,
  },
  {
    id: 35,
    title: "Tomato Almond Surprise Salad",
    contributor: "Melba",
    category: "Salad",
    servings: null,
    temps: "Refrigerate till set",
    ingredients: [
      { amount: "1 pkge", item: "lemon jello" },
      { amount: "1 can", item: "tomato soup" },
      { amount: "½ tsp", item: "gelatin" },
      { amount: "8 oz", item: "cream cheese" },
      { amount: "1½ c", item: "diced celery" },
      { amount: "4–6", item: "chopped green onions" },
      { amount: "½ c", item: "almonds chopped" },
      { amount: "1", item: "green pepper diced" },
      { amount: "1 c", item: "Miracle Whip" },
    ],
    steps: [
      "Mix first 3 ingredients in a saucepan, heat until hot.",
      "Whip the cream cheese and heat in jello mixture.",
      "Add remaining ingredients and pour into jello mould.",
    ],
    notes: null,
  },
  {
    id: 36,
    title: "24 Hour Salad",
    contributor: "Karen",
    category: "Salad",
    servings: null,
    temps: "Refrigerate 24 hours",
    ingredients: [
      { amount: "1 head", item: "of lettuce" },
      { amount: "1 c", item: "diced celery" },
      { amount: "1 c", item: "green pepper (diced)" },
      { amount: "1 c", item: "chopped spanish onion" },
      { amount: "1 c", item: "frozen peas" },
      { amount: "1 c", item: "grated carrot" },
      { amount: "1 c", item: "mayonnaise (NOT MIRACLE WHIP)" },
      { amount: "1 tbsp", item: "sugar" },
      { amount: "½ lb", item: "bacon" },
      { amount: "1 c", item: "grated cheddar cheese" },
    ],
    steps: [
      "Fry the bacon until crisp. Break it up into pieces.",
      "Tear lettuce in bite size pieces. Layer the ingredients in the order given, in a LARGE DEEP bowl.",
      "Cover with saran wrap for 24 hours. DO NOT PEEK!!",
      "When serving, make sure to tell your guests to dig right to the bottom of the bowl to make sure they get a taste of everything.",
      "This will keep up to a week in the fridge without the lettuce wilting.",
    ],
    notes: null,
  },
  {
    id: 37,
    title: "Tomato Aspic Salad",
    contributor: "Melba",
    category: "Salad",
    servings: null,
    temps: "Refrigerate till set",
    ingredients: [
      { amount: "1 pkge", item: "lemon jello" },
      { amount: "1 – 19 oz tin", item: "tomato juice" },
      { amount: "1 tbsp", item: "vinegar" },
      { amount: "1 – 4 oz tin", item: "large or medium shrimp" },
      { amount: "4", item: "green onions chopped fine" },
      { amount: "½ c", item: "celery chopped fine" },
    ],
    steps: [
      "Heat juice to boiling, mix with jello and refrigerate until partially set.",
      "Add all other remaining ingredients and pour into mould.",
    ],
    notes: null,
  },
  {
    id: 38,
    title: "Vegetable Salad",
    contributor: "Karen",
    category: "Salad",
    servings: null,
    temps: "Refrigerate 24 hours",
    ingredients: [
      { amount: "1 large head", item: "cauliflower" },
      { amount: "1 basket", item: "cherry tomatoes" },
      { amount: "1 bunch", item: "broccoli" },
      { amount: "4", item: "carrots" },
      { amount: "3 stalks", item: "of celery" },
      { amount: "2 cans", item: "button mushrooms" },
      { amount: "1 – 8 oz bottle", item: "Italian dressing" },
      { amount: "1 can", item: "pitted black olives drained" },
    ],
    steps: [
      "Cut cauliflower, broccoli with peeled stems, carrots, celery into bite size pieces.",
      "Mix all the ingredients in a double plastic bag or a Tupperware marinate dish.",
      "Refrigerate for 24 hours, turning the bag frequently to ensure the vegetables are all marinated.",
      "Drain off excess dressing before serving.",
    ],
    notes: null,
  },
  {
    id: 39,
    title: "Coleslaw",
    contributor: "Karen",
    category: "Salad",
    servings: null,
    temps: "Refrigerate 3 hours",
    ingredients: [
      { amount: "3 lb", item: "cabbage" },
      { amount: "2 small", item: "onions" },
      { amount: "2", item: "carrots" },
      { amount: "3/4 c", item: "sugar" },
      { amount: "1 c", item: "vinegar" },
      { amount: "2 tsp", item: "mustard seed" },
      { amount: "2 tsp", item: "celery seed" },
      { amount: "1 tsp", item: "salt" },
      { amount: "¼ c", item: "sugar" },
      { amount: "3/4 c", item: "oil" },
    ],
    steps: [
      "Shred the cabbage and carrots and chop up the onion. Combine in a bowl and add the 3/4 c sugar, mixing well. Set aside while preparing the dressing.",
      "Combine vinegar, mustard seed, celery seed, salt and ¼ c sugar (all but oil). Bring to a boil and add the oil. Boil 3 minutes. Pour this over the cabbage mixture.",
      "Let this refrigerate for at least 3 hours before using.",
    ],
    notes: "THIS WILL KEEP IN THE REFRIGERATOR FOR ONE MONTH!!",
  },
  {
    id: 40,
    title: "Drop Cookies",
    contributor: "Mom Burroughs",
    category: "Cookies",
    servings: null,
    temps: "350° for 15 minutes",
    ingredients: [
      { amount: "1 c", item: "raisins" },
      { amount: "2 c", item: "flour" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "½ tsp", item: "nutmeg" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "½ tsp", item: "cloves" },
      { amount: "½ c", item: "walnuts" },
      { amount: "½ c", item: "butter" },
      { amount: "½ c", item: "sugar" },
      { amount: "2", item: "eggs" },
    ],
    steps: [
      "Cover raisins with water and boil 15 minutes. Cool in fridge until cold.",
      "Beat butter, sugar & eggs in a small bowl.",
      "Mix all dry ingredients in a large separate bowl.",
      "Mix all ingredients together in the large bowl and bake. You may need to add more flour to make a stiff cookie dough.",
    ],
    notes: "Yield: 3½ dozen.",
  },
  {
    id: 41,
    title: "Ginger Snaps",
    contributor: "Lorna",
    category: "Cookies",
    servings: null,
    temps: "350° for 8–10 minutes",
    ingredients: [
      { amount: "2 c", item: "flour" },
      { amount: "1 tsp", item: "ginger" },
      { amount: "2 tsp", item: "soda" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "½ tsp", item: "salt" },
      { amount: "3/4 c", item: "lard" },
      { amount: "1 c", item: "white sugar" },
      { amount: "1", item: "egg" },
      { amount: "¼ c", item: "molasses" },
    ],
    steps: [
      "Mix lard, sugar, then egg and dry ingredients.",
      "Roll dough in balls, then sugar.",
      "Place on cookie sheet, slightly flatten and bake.",
      "When finished baking, remove from pan immediately.",
    ],
    notes: null,
  },
  {
    id: 42,
    title: "No Bake Cookies",
    contributor: "Lorna",
    category: "Cookies",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 c", item: "sugar" },
      { amount: "1 c", item: "corn syrup" },
      { amount: "1 c", item: "peanut butter" },
      { amount: "4½ c", item: "Kellogg's Special \"K\"" },
    ],
    steps: [
      "In 2 quart saucepan, place sugar and corn syrup.",
      "Stir constantly while on low heat until sugar is no longer granular. Remove from heat and stir in peanut butter and Special \"K\" cereal.",
      "Spoon onto cookie sheet, shape and store between wax paper in tightly closed container.",
    ],
    notes: null,
  },
  {
    id: 43,
    title: "Shortbread",
    contributor: "Mom Burroughs",
    category: "Cookies",
    servings: null,
    temps: "300° for 15–20 minutes",
    ingredients: [
      { amount: "1 c", item: "brown sugar" },
      { amount: "2 c", item: "butter" },
      { amount: "4 c", item: "flour" },
    ],
    steps: [
      "Leave butter sit for 24 hours before using.",
      "Mix sugar and flour by hand and slowly add butter and mix by hand.",
      "Take a piece at a time and knead it (the more you knead it, the better it will be). Refrigerate for a while.",
      "Roll out or pat and cut with small cookie cutter, then prick with fork.",
      "Bake till golden brown on ungreased cookie sheet.",
    ],
    notes: null,
  },
  {
    id: 44,
    title: "Saucepan Cookies",
    contributor: "Beryl",
    category: "Cookies",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "2 c", item: "brown sugar" },
      { amount: "½ c", item: "milk" },
      { amount: "½ c", item: "butter" },
      { amount: "½ c", item: "cocoa" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "½ tsp", item: "salt" },
      { amount: "3 c", item: "rolled oats" },
      { amount: "1 c", item: "coconut" },
    ],
    steps: [
      "Combine first 6 ingredients in saucepan and boil for 5 minutes. Add other ingredients and stir.",
      "Drop on wax paper by teaspoons. Chill until set.",
    ],
    notes: null,
  },
  {
    id: 45,
    title: "Mona's Mother's Best Friend's Favorite Cookies",
    contributor: "Lorna",
    category: "Cookies",
    servings: null,
    temps: "350° until golden brown",
    ingredients: [
      { amount: "1 c", item: "sugar" },
      { amount: "½ c", item: "brown sugar" },
      { amount: "1", item: "egg" },
      { amount: "1 c", item: "butter" },
      { amount: "1 c", item: "flour (may need ½ c or more)" },
      { amount: "1¼ c", item: "quick rolled oats" },
      { amount: "3/4 c", item: "coconut" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "baking soda" },
    ],
    steps: [
      "Mix all ingredients together in order and drop on cookie sheet by teaspoons. Bake.",
    ],
    notes: "You may need to use ½ cup or more of flour.",
  },
  {
    id: 46,
    title: "Not So Sweet Frosting",
    contributor: "Lorna",
    category: "Cakes & Frostings",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 c", item: "milk" },
      { amount: "6 tbsp", item: "flour" },
      { amount: "½ c", item: "crisco" },
      { amount: "½ c", item: "margarine" },
      { amount: "2 tsp", item: "vanilla" },
      { amount: "2 c", item: "icing sugar" },
    ],
    steps: [
      "Cook milk and flour together, stirring constantly, making a thick paste.",
      "Beat crisco, margarine, vanilla & icing sugar in a bowl at high speed 5–10 minutes. Add cooled flour mixture, beat 3–5 minutes more.",
    ],
    notes: null,
  },
  {
    id: 47,
    title: "Cake Topping",
    contributor: "Phyllis",
    category: "Cakes & Frostings",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 envelope", item: "whipped topping mix" },
      { amount: "1 small pkg.", item: "instant pudding mix" },
      { amount: "1½ c", item: "cold milk" },
    ],
    steps: [
      "In chilled bowl blend and whip the whipped topping mix and the instant pudding mix with the cold milk until stiff.",
      "Immediately frost cake and store in refrigerator.",
    ],
    notes: null,
  },
  {
    id: 48,
    title: "Carmel Icing",
    contributor: "Gail",
    category: "Cakes & Frostings",
    servings: null,
    temps: "Boil 1 minute",
    ingredients: [
      { amount: "1 c", item: "brown sugar" },
      { amount: "3 tbsp", item: "cream" },
      { amount: "3 tbsp", item: "butter" },
      { amount: "a bit", item: "icing sugar & cream" },
    ],
    steps: [
      "Combine and boil all ingredients for 1 minute. Let cool slightly and beat until desired consistency.",
    ],
    notes: null,
  },
  {
    id: 49,
    title: "Rolled Oats Cake",
    contributor: "Gail",
    category: "Cakes & Frostings",
    servings: null,
    temps: "375° for 10–15 minutes",
    ingredients: [
      { amount: "3/4 c", item: "brown sugar" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "2 c", item: "rolled oats" },
      { amount: "½ c", item: "butter" },
      { amount: "½ tsp", item: "vanilla" },
    ],
    steps: [
      "Combine all ingredients. Pat into 8 X 8 ungreased pan.",
    ],
    notes: null,
  },
  {
    id: 50,
    title: "Burroughs' Christmas/Wedding Cake",
    contributor: "Mom Burroughs",
    category: "Cakes & Frostings",
    servings: null,
    temps: "300° for 3–4 hours",
    ingredients: [
      { amount: "1 lb", item: "currants" },
      { amount: "1 lb", item: "dates" },
      { amount: "1 lb", item: "seeded puffed raisins" },
      { amount: "1 lb", item: "raisins" },
      { amount: "1 lb", item: "mixed fruit" },
      { amount: "1", item: "grated rind of one orange" },
      { amount: "1", item: "grated rind of one lemon" },
      { amount: "1 c", item: "walnuts" },
      { amount: "1 c", item: "almonds" },
      { amount: "1 c + 3 heaping c", item: "flour (divided)" },
      { amount: "1 tsp", item: "salt" },
      { amount: "4 tsp", item: "cocoa" },
      { amount: "2 tsp", item: "cinnamon" },
      { amount: "1½ tsp", item: "baking powder" },
      { amount: "½ tsp", item: "nutmeg" },
      { amount: "½ tsp", item: "cloves" },
      { amount: "½ tsp", item: "allspice" },
      { amount: "½ tsp", item: "ginger" },
      { amount: "1 lb", item: "butter" },
      { amount: "2¼ c", item: "sugar" },
      { amount: "10", item: "eggs" },
      { amount: "1 c", item: "grape juice" },
      { amount: "1", item: "juice of one lemon" },
      { amount: "1", item: "juice of one orange" },
    ],
    steps: [
      "Mix fruits, orange and lemon rinds, walnuts, almonds and 1 c flour in a bowl.",
      "Sift together the salt, cocoa, cinnamon, baking powder, nutmeg, cloves, allspice, ginger and 3 heaping c flour in another bowl.",
      "Cream butter and sugar and add well beaten eggs in a large bowl.",
      "To the butter mixture, add the dry flour/spice mixture, then add the fruit mixture. Mix well.",
      "Mix the grape juice, lemon juice and orange juice and add to the combined mixture.",
      "Line the pans (sides and bottom) with brown paper then wax paper. Bake in three layer cake pans (small, medium and large). ENSURE a pan of hot water is in the oven during the entire time to provide moisture to the cakes.",
      "You may need to turn the oven down to 250° if the cakes are browning too fast.",
    ],
    notes: "THIS IS A DARK CHRISTMAS CAKE.",
  },
  {
    id: 51,
    title: "Grandma Johnson's Christmas Cake",
    contributor: "Beryl",
    category: "Cakes & Frostings",
    servings: null,
    temps: "300° for 2 hrs., then 250° until done",
    ingredients: [
      { amount: "1½ lbs", item: "butter" },
      { amount: "3 c", item: "sugar" },
      { amount: "14", item: "eggs" },
      { amount: "4 c", item: "flour" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "½ tsp", item: "lemon juice" },
      { amount: "2 lbs", item: "raisins (Australian Suttan)" },
      { amount: "1 lb", item: "currants" },
      { amount: "2 lbs", item: "mixed fruit" },
      { amount: "1 lb", item: "cherries" },
      { amount: "1 pkg", item: "almonds" },
    ],
    steps: [
      "Add flour to clean fruit.",
      "Beat butter, sugar & eggs.",
      "Add all ingredients to fruit.",
      "Wax paper line 5 loaf pans, pour in, and bake.",
    ],
    notes: "THIS IS A LIGHT CAKE.",
  },
  {
    id: 52,
    title: "Carrot Cake & Frosting",
    contributor: "Fran",
    category: "Cakes & Frostings",
    servings: null,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "1 c", item: "corn oil" },
      { amount: "1 c", item: "sugar" },
      { amount: "3", item: "eggs" },
      { amount: "1½ c", item: "flour" },
      { amount: "1½ tsp", item: "soda" },
      { amount: "1½ tsp", item: "baking powder" },
      { amount: "3/4 tsp", item: "salt" },
      { amount: "1½ tsp", item: "cinnamon" },
      { amount: "½ c", item: "nuts" },
      { amount: "2 c", item: "raw grated carrots" },
      { amount: "1 tsp", item: "almond extract" },
    ],
    steps: [
      "Beat the corn oil at a low speed with mixer. Add the white sugar, and the 3 eggs, one at a time.",
      "Sift together the flour, soda, baking powder and salt. Add these dry ingredients to the wet mixture. Add cinnamon and nuts, blend well.",
      "Pour the almond extract over the carrots. Add to the other ingredients and mix thoroughly. Pour into 13 X 9 pan and bake.",
      "Icing: Cream together 1 pkg cream cheese, ¼ c butter, 1½ c icing sugar and 1 tsp vanilla. Beat well and spread on cooled cake.",
    ],
    notes: null,
  },
  {
    id: 53,
    title: "Crazy Chocolate Cake",
    contributor: "Kim",
    category: "Cakes & Frostings",
    servings: null,
    temps: "325° for 25–30 minutes",
    ingredients: [
      { amount: "1 c", item: "miracle whip" },
      { amount: "1 c", item: "sugar" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "2¼ c", item: "flour" },
      { amount: "½ c", item: "cocoa" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "dash", item: "salt" },
      { amount: "3/4 c", item: "cold water" },
    ],
    steps: [
      "Combine miracle whip, sugar and vanilla. Sift together flour, cocoa, baking soda, baking powder and salt. Add to first mixture alternating with water, mixing well after each addition.",
      "Pour into greased 9 X 13 pan or 2 – 8\" layer pans.",
      "Cocoa Butter Icing: Mix together 1/3 c soft butter and 1/3 c cocoa. Blend in 2 c sifted icing sugar, then stir in 1½ tsp vanilla and 2 tbsp milk. Beat until smooth and of spreading consistency.",
    ],
    notes: null,
  },
  {
    id: 54,
    title: "White Cake",
    contributor: "Lorna",
    category: "Cakes & Frostings",
    servings: null,
    temps: "350° for 45 minutes",
    ingredients: [
      { amount: "2½ c", item: "flour" },
      { amount: "3 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "salt" },
      { amount: "1 2/3 c", item: "sugar" },
      { amount: "2/3 c", item: "shortening" },
      { amount: "3", item: "eggs" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "1 1/3 c", item: "milk" },
    ],
    steps: [
      "Cream shortening, sugar, salt and vanilla well, add eggs, beating well after each addition.",
      "Add dry ingredients alternately with milk. Mix well but don't overbeat. Pour in 9 X 13 pan and bake.",
      "For easy removal from pan, paper bottom of pan before putting batter in.",
    ],
    notes: null,
  },
  {
    id: 55,
    title: "Carrot Cake",
    contributor: "Cally",
    category: "Cakes & Frostings",
    servings: null,
    temps: "300° for 1 hour",
    ingredients: [
      { amount: "1 c", item: "sugar" },
      { amount: "1 c", item: "cooking oil" },
      { amount: "3", item: "eggs" },
      { amount: "1 1/3 c", item: "flour" },
      { amount: "½ tsp", item: "salt" },
      { amount: "1 1/3 tsp", item: "soda" },
      { amount: "1 1/3 tsp", item: "baking powder" },
      { amount: "1 1/3 tsp", item: "cinnamon" },
      { amount: "2 c", item: "grated carrot" },
      { amount: "½ c", item: "walnuts" },
    ],
    steps: [
      "Combine sugar & oil, beat. Beat in eggs, one at a time. Add sifted dry ingredients to mixture and beat well.",
      "Fold in carrots and chopped nuts. Bake in oblong pan or 2 layer pans.",
      "Icing: Beat together 1 – 8 oz pkg cream cheese (softened), ¼ c butter, 2 tsp vanilla and 1 box icing sugar. Spread over cake.",
    ],
    notes: "Use ½ icing recipe for oblong pan, full recipe for 2 layer tins.",
  },
  {
    id: 56,
    title: "Sour Cream Banana Cake",
    contributor: "Shirley",
    category: "Cakes & Frostings",
    servings: null,
    temps: "350° for 25–35 minutes",
    ingredients: [
      { amount: "¼ c", item: "shortening" },
      { amount: "1 1/3 c", item: "sugar" },
      { amount: "2", item: "eggs" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "2 c", item: "flour" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "3/4 tsp", item: "salt" },
      { amount: "1 c", item: "sour cream" },
      { amount: "1 c", item: "mashed bananas" },
      { amount: "½ c", item: "chopped pecans" },
    ],
    steps: [
      "Cream shortening and sugar until light and fluffy. Add eggs and vanilla; blend thoroughly. Combine flour, baking powder, baking soda and salt. Add to creamed mixture alternately with sour cream beginning and ending with dry ingredients.",
      "Add bananas and pecans mixing just until blended.",
      "Spoon batter into a greased 9 X 13 pan, bake.",
      "Icing: Combine 1 – 8 oz pkg cream cheese (softened), ¼ c melted margarine, 1 tsp vanilla and 1 lb box powdered sugar. Blend well.",
    ],
    notes: null,
  },
  {
    id: 57,
    title: "Strawberry Shortcake",
    contributor: "Mom Burroughs",
    category: "Cakes & Frostings",
    servings: null,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "½ c", item: "margarine (soft)" },
      { amount: "1 c", item: "sugar" },
      { amount: "2", item: "eggs (beaten)" },
      { amount: "½ c", item: "milk" },
      { amount: "2 c", item: "flour" },
      { amount: "2 tsp", item: "baking powder" },
      { amount: "½ tsp", item: "salt" },
    ],
    steps: [
      "Cream margarine and sugar in large bowl.",
      "Mix dry ingredients in small bowl.",
      "Beat eggs and milk in small bowl.",
      "Alternating add dry and wet ingredients to margarine and sugar mixture, mixing well after each addition.",
      "Once all the ingredients are well blended, pour into a greased 9 X 12 pan and bake until a toothpick comes out clean and the cake is golden brown.",
      "Serve with prepared strawberries and whip cream.",
    ],
    notes: null,
  },
  {
    id: 58,
    title: "Fluffy White Cake & Frosting",
    contributor: "Karen",
    category: "Cakes & Frostings",
    servings: null,
    temps: "350° for 25 minutes",
    ingredients: [
      { amount: "2", item: "eggs (beaten)" },
      { amount: "1 c", item: "sugar" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "1 c", item: "flour" },
      { amount: "½ c", item: "milk" },
      { amount: "3 tbsp", item: "margarine" },
      { amount: "1 tsp", item: "vanilla" },
    ],
    steps: [
      "Bring the milk and margarine to a boil. Set aside to slightly cool.",
      "Beat the eggs thoroughly, add sugar, beat well. Add the remaining dry ingredients and beat really well.",
      "Add the boiled milk-margarine, beat well and add vanilla.",
      "Pour into a greased 8 X 8 pan and bake until golden brown.",
      "Icing: Melt ¼ c margarine in a saucepan, add ½ c brown sugar and stir over low heat for 2 minutes. Add 2 tbsp milk and stir constantly until it comes to a boil. Remove from heat. Add 1¼ c icing sugar and 1 tsp vanilla. Beat until creamy. Pour over cooled cake. Sprinkle on ¼ c chopped walnuts (optional).",
    ],
    notes: "THE ICING IS NOT STIFF LIKE MOST – but it will harden on the cake.",
  },
  {
    id: 59,
    title: "Pumpkin Pie",
    contributor: "Mom Burroughs",
    category: "Pies & Desserts",
    servings: null,
    temps: "425° for 15 minutes, then 350° for 45 minutes",
    ingredients: [
      { amount: "2 c", item: "pumpkin" },
      { amount: "3 c", item: "boiled milk" },
      { amount: "6", item: "eggs" },
      { amount: "1½ c", item: "sugar" },
      { amount: "1 tbsp each", item: "ginger, nutmeg, cinnamon" },
      { amount: "1 c", item: "cream or evaporated milk" },
    ],
    steps: [
      "Mix all ingredients except boiled milk. Blend thoroughly with mixer.",
      "Mix in boiled milk.",
      "Bake until knife inserted in middle comes out clean.",
    ],
    notes: "USE ONLY LIBBY'S PUMPKIN FOR BEST RESULTS.",
  },
  {
    id: 60,
    title: "Pie Crust",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "5 c", item: "flour" },
      { amount: "2 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "salt" },
      { amount: "2 tbsp", item: "sugar (optional)" },
      { amount: "1 lb", item: "lard (Tenderflake)" },
      { amount: "1", item: "egg" },
      { amount: "1 tbsp", item: "vinegar" },
      { amount: "to fill 1 cup", item: "water" },
    ],
    steps: [
      "In large bowl mix flour, baking powder, salt, sugar, mixing well. Add lard and mix by hand to make pea like consistency.",
      "In a one cup measuring cup, slightly beat egg, add vinegar and fill to one cup with cool water.",
      "Add water mixture to flour mixture and mix by hand until well blended. (You may need to add a little more flour.) DO NOT OVERWORK your pastry.",
      "This can be refrigerated for 2–3 weeks or frozen.",
    ],
    notes: "Yield: 3 double pie crusts.",
  },
  {
    id: 61,
    title: "Pumpkin Pie",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "425° for 15 minutes, then 350° for 45 minutes",
    ingredients: [
      { amount: "14 oz can", item: "Libby's pumpkin" },
      { amount: "2", item: "eggs (beaten)" },
      { amount: "3/4 c", item: "sugar" },
      { amount: "½ tsp", item: "salt" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "½ tsp", item: "ginger" },
      { amount: "¼ tsp", item: "cloves" },
      { amount: "14 oz can", item: "evaporated milk" },
    ],
    steps: [
      "Mix ingredients in order given with an electric beater. Pour into deep pastry shell. Bake until knife inserted comes out clean.",
    ],
    notes: null,
  },
  {
    id: 62,
    title: "Simple Blueberry Pudding",
    contributor: "Gail",
    category: "Pies & Desserts",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "2 c", item: "frozen blueberries" },
      { amount: "¼ c", item: "water" },
      { amount: "¼ c", item: "sugar" },
      { amount: "1–2 tbsp", item: "cornstarch mixed with a little water" },
      { amount: "1 c", item: "whipping cream" },
      { amount: "6", item: "soda crackers" },
    ],
    steps: [
      "Cook the blueberries, water & sugar. Add the cornstarch and cook until thickened. Let cool completely.",
      "Prepare the whipping cream adding sugar and vanilla to taste. Take the soda crackers and make fine crumbs.",
      "Sprinkle soda cracker crumbs on bottom of bowl, then half of the blueberries & half of the whipping cream. REPEAT. (Ingredients should be prepared ahead of time but assemble just before serving.)",
    ],
    notes: null,
  },
  {
    id: 63,
    title: "Apple Pie",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "425° for 15 minutes, then 350° for 45 minutes",
    ingredients: [
      { amount: "8–10", item: "apples" },
      { amount: "3 tsp", item: "cinnamon" },
      { amount: "½ tsp", item: "nutmeg" },
      { amount: "3 tbsp", item: "tapioca" },
      { amount: "1 c", item: "sugar" },
    ],
    steps: [
      "Mix dry ingredients, then mix with sliced apples.",
      "Pour into uncooked pie crust and bake.",
    ],
    notes: null,
  },
  {
    id: 64,
    title: "Pecan Crisps",
    contributor: "Gail",
    category: "Pies & Desserts",
    servings: null,
    temps: "300° for 30–35 minutes",
    ingredients: [
      { amount: "1 c", item: "butter" },
      { amount: "¼ c", item: "sugar" },
      { amount: "½ tsp", item: "vanilla" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "2 c", item: "flour" },
      { amount: "1 c", item: "chopped pecans" },
      { amount: "to taste", item: "icing sugar" },
    ],
    steps: [
      "Cream butter, add sugar gradually and beat mixture well. Stir in vanilla, salt, flour and pecans, blend thoroughly.",
      "Roll into balls, flatten & bake. While still warm, roll in icing sugar.",
      "Once you have flattened the balls, you can trim around the edge with a small tupperware container so they are perfectly round.",
    ],
    notes: null,
  },
  {
    id: 65,
    title: "Cheesecake Cupcakes",
    contributor: "Lorna",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 18–20 minutes",
    ingredients: [
      { amount: "to line pan", item: "medium paper muffin cups" },
      { amount: "1 per cup", item: "vanilla wafers" },
      { amount: "1 c", item: "sugar" },
      { amount: "2 – 8 oz pkg", item: "cream cheese" },
      { amount: "3", item: "eggs" },
      { amount: "2 tsp", item: "lemon juice" },
      { amount: "1 can", item: "cherry pie filling" },
    ],
    steps: [
      "Mix sugar, eggs, cheese and lemon. Line cupcake pans with papers. Place one vanilla wafer in each. Spoon cheese mixture over wafers (about 2/3 full).",
      "Bake 18–20 minutes, cool and spoon pie filling on each cupcake (other kinds of pie filling may be used). Refrigerate for 1 hour.",
    ],
    notes: null,
  },
  {
    id: 66,
    title: "Wheat Germ Muffins",
    contributor: "Shirley & Corinne",
    category: "Pies & Desserts",
    servings: null,
    temps: "350°–375° for 15 minutes",
    ingredients: [
      { amount: "1 c", item: "sifted flour" },
      { amount: "3 tsp", item: "baking powder" },
      { amount: "1/8 tsp", item: "baking soda" },
      { amount: "½ c", item: "wheat germ" },
      { amount: "3/4 c", item: "brown sugar" },
      { amount: "1", item: "egg" },
      { amount: "3/4 c", item: "milk" },
      { amount: "¼ c", item: "salad oil" },
      { amount: "½ c", item: "raisins" },
    ],
    steps: [
      "Sift dry ingredients, add liquid, oil & raisins. Mix only to blend. Bake.",
    ],
    notes: "I DOUBLE THE RECIPE.",
  },
  {
    id: 67,
    title: "Cinnamon Loaf",
    contributor: "Phyllis",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 1 hour",
    ingredients: [
      { amount: "3 tbsp", item: "brown sugar" },
      { amount: "1 tbsp", item: "cinnamon" },
      { amount: "¼ c", item: "butter" },
      { amount: "1 c", item: "sugar" },
      { amount: "2", item: "eggs" },
      { amount: "1 c", item: "sour milk" },
      { amount: "2 tsp", item: "vanilla" },
      { amount: "2 c", item: "flour" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "1 tsp", item: "salt" },
    ],
    steps: [
      "Mix the brown sugar and cinnamon and set aside.",
      "Cream the butter and the white sugar, add the eggs and beat well. Set aside.",
      "Mix the flour, baking powder, baking soda and salt.",
      "Alternating, add sour milk and flour mixture to the butter mixture, mixing well after each.",
      "Pour 1/3 of batter in a pan and sprinkle with ½ the cinnamon mixture. Add another 1/3 of batter then the rest of the cinnamon. Pour the last of the batter on and bake.",
    ],
    notes: null,
  },
  {
    id: 68,
    title: "Lemon Loaf",
    contributor: "Kim",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 1¼ hours",
    ingredients: [
      { amount: "½ c", item: "shortening" },
      { amount: "2", item: "eggs" },
      { amount: "1½ c", item: "flour" },
      { amount: "½ tsp", item: "salt" },
      { amount: "1 c", item: "sugar" },
      { amount: "to taste", item: "grated lemon rind" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "½ c", item: "milk" },
    ],
    steps: [
      "Cream shortening and sugar and add eggs and lemon rind. Beat well.",
      "Alternate dry and liquid ingredients.",
      "Bake.",
      "When loaf comes out of oven, over hot loaf pour approximately ½ cup sugar and moisten with lemon juice.",
      "Return to oven for additional 5 minutes.",
    ],
    notes: null,
  },
  {
    id: 69,
    title: "Walnut Loaf",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 60–70 minutes",
    ingredients: [
      { amount: "3 c", item: "flour" },
      { amount: "1 c", item: "sugar" },
      { amount: "4 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "salt" },
      { amount: "3/4 c", item: "margarine" },
      { amount: "1½ c", item: "walnuts (divided: 1¼ c + ¼ c)" },
      { amount: "1", item: "egg beaten" },
      { amount: "1½ c", item: "milk" },
      { amount: "1 tsp", item: "vanilla" },
    ],
    steps: [
      "Mix flour, sugar, baking powder and salt. Cut in margarine.",
      "Stir in 1¼ c walnuts. Add egg and milk.",
      "Mix until JUST blended.",
      "Turn into greased and floured 9 x 5 loaf pan.",
      "Sprinkle ¼ c walnuts and bake.",
    ],
    notes: null,
  },
  {
    id: 70,
    title: "Rye Bread",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "375° for 35–40 minutes",
    ingredients: [
      { amount: "2 tbsp", item: "dry yeast" },
      { amount: "1 tbsp", item: "salt" },
      { amount: "2 tbsp", item: "honey" },
      { amount: "2 c", item: "warm water" },
      { amount: "2/3 c", item: "instant skim milk powder" },
      { amount: "½ c", item: "vegetable oil" },
      { amount: "½ c", item: "wheat germ" },
      { amount: "1 c", item: "rye flour OR whole wheat flour OR graham flour" },
      { amount: "4 c", item: "white flour (all purpose)" },
    ],
    steps: [
      "In large bowl mix yeast, salt and honey. Add water and stir in skim milk powder, then oil. Stir in wheat germ and rye flour then all purpose flour.",
      "Turn onto lightly floured board and knead 10 minutes, adding flour as dough becomes sticky (½ – 1 cup).",
      "NOTE: The dough should be soft and elastic (Not Dry).",
      "Let rest while you grease and flour three loaf pans. Divide dough into three pans.",
      "Cover loosely with greased wax paper and let rise in fridge overnight (Minimum 5 hours – Maximum 24 hours).",
      "Bake.",
    ],
    notes: null,
  },
  {
    id: 71,
    title: "Tea Biscuits",
    contributor: "Melba",
    category: "Pies & Desserts",
    servings: null,
    temps: "450° for 10–14 minutes",
    ingredients: [
      { amount: "2 c", item: "flour" },
      { amount: "1 tbsp", item: "sugar" },
      { amount: "4 tsp", item: "baking powder" },
      { amount: "½ tsp", item: "salt" },
      { amount: "½ c", item: "margarine" },
      { amount: "1", item: "egg" },
      { amount: "1 tbsp", item: "vinegar" },
      { amount: "2/3 c", item: "milk" },
    ],
    steps: [
      "Mix dry ingredients, cut in margarine, and combine milk, egg and vinegar and add to other mixture.",
      "Stir until dough follows fork around the bowl.",
      "Turn onto lightly floured board.",
      "Knead 20 strokes. (NO MORE)",
      "Roll 3/4\" thick, dip 2\" cutter in flour and cut.",
      "Put on ungreased baking sheets and bake.",
    ],
    notes: null,
  },
  {
    id: 72,
    title: "Chocolate Mint Dessert",
    contributor: "Melba",
    category: "Pies & Desserts",
    servings: null,
    temps: "Chill minimum 6 hours",
    ingredients: [
      { amount: "1½ c", item: "chocolate wafers crushed" },
      { amount: "½ c", item: "crushed after dinner mints (plain white only)" },
      { amount: "3 tbsp", item: "butter (melted)" },
      { amount: "½ pint", item: "whipping cream" },
    ],
    steps: [
      "Mix the chocolate wafers and the butter together and spread ½ of the mixture in a 8 x 8 pan.",
      "Fold the crushed after dinner mints into the whipped cream. Spread on top of the crust and sprinkle the remaining wafers on top.",
      "Chill until set. Minimum 6 hours.",
    ],
    notes: "Do Not Use Dream Whip. Also use only plain white after dinner mints.",
  },
  {
    id: 73,
    title: "Apple Crumble",
    contributor: "Carrie",
    category: "Pies & Desserts",
    servings: null,
    temps: "375° for 25–30 minutes",
    ingredients: [
      { amount: "4 or 5", item: "apples" },
      { amount: "¼ c", item: "sugar" },
      { amount: "1 oz", item: "water" },
      { amount: "¼ tsp", item: "cloves" },
      { amount: "½ c", item: "flour" },
      { amount: "3/4 c", item: "rolled oats" },
      { amount: "dash", item: "of salt" },
      { amount: "½ c", item: "brown sugar" },
      { amount: "½ c", item: "melted margarine" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "¼ c", item: "sugar (for lemon sauce)" },
      { amount: "1½ tbsp", item: "cornstarch (for lemon sauce)" },
      { amount: "1 c", item: "water (for lemon sauce)" },
      { amount: "1½ tbsp", item: "lemon juice (for lemon sauce)" },
    ],
    steps: [
      "Slice apples, place in casserole dish, sprinkle with water, sugar and cloves.",
      "To prepare topping, combine dry ingredients (flour, oats, salt, brown sugar, cinnamon), add melted butter. Sprinkle topping over fruit. Bake.",
      "To prepare Lemon Sauce, combine sugar, cornstarch and water in double boiler. Cook over heat until thickened. Add lemon juice. Pour over baked fruit when serving.",
    ],
    notes: null,
  },
  {
    id: 74,
    title: "English Trifle",
    contributor: "Cally",
    category: "Pies & Desserts",
    servings: null,
    temps: "Chill overnight",
    ingredients: [
      { amount: "1 small", item: "sponge cake (from bakery)" },
      { amount: "1 pkg", item: "frozen raspberries, thawed & well drained" },
      { amount: "4 tbsp", item: "icing sugar" },
      { amount: "½–1 c", item: "raspberry jam" },
      { amount: "½ c", item: "sherry" },
      { amount: "1 pkg", item: "vanilla instant pudding" },
      { amount: "2 c", item: "whipping cream" },
      { amount: "to taste", item: "toasted almonds and maraschino cherries" },
    ],
    steps: [
      "Beat vanilla instant pudding and chill until firm. Cut cake into 1 inch finger slices. Spread with raspberry jam on one side. Place half of cake slices, jam side up in serving bowl.",
      "Sprinkle with half of sherry. Cover with ½ of berries then half of pudding. Whip cream and sweeten with icing sugar. Spread half over custard.",
      "Repeat layers. Put whipping cream on top and garnish with toasted almond and cherries. Chill overnight.",
    ],
    notes: "Use a deep attractive see-through bowl.",
  },
  {
    id: 75,
    title: "Cherries in the Snow",
    contributor: "Corinne",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 6–8 minutes",
    ingredients: [
      { amount: "1½–2 pkg", item: "graham crackers" },
      { amount: "1 stick", item: "butter or margarine" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "to taste", item: "powdered sugar" },
      { amount: "2 pkg (8 oz.)", item: "cream cheese" },
      { amount: "1 tsp", item: "lemon extract" },
      { amount: "½ pkg", item: "dream whip" },
      { amount: "1 can", item: "cherries" },
    ],
    steps: [
      "Mix graham crackers with melted butter to make crust.",
      "Mix ingredients and pour over crust. Top with whipping cream and one can of cherries.",
      "Refrigerate.",
    ],
    notes: null,
  },
  {
    id: 76,
    title: "Strawberry Square Dessert",
    contributor: "Melba",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 15 minutes; Freeze 6 hours",
    ingredients: [
      { amount: "1 c", item: "flour" },
      { amount: "½ c", item: "chopped walnuts" },
      { amount: "2", item: "egg whites" },
      { amount: "2 c", item: "sliced strawberries or 1–10 oz. pkg frozen berries" },
      { amount: "¼ c", item: "brown sugar" },
      { amount: "½ c", item: "melted butter" },
      { amount: "1 c", item: "sugar" },
      { amount: "2 tbsp", item: "lemon juice" },
      { amount: "1 c", item: "cream whipped" },
    ],
    steps: [
      "Stir flour, brown sugar, chopped walnuts and melted butter. Spread on 13 x 9 pan. Bake 350° stirring every 5 minutes about 15 minutes.",
      "Combine egg whites, beat and add sugar, berries and lemon juice. Beat 10 minutes. Fold in whipped cream.",
      "Pour over 3/4 of crumbs and top with remaining crumbs.",
      "Freeze 6 hours. This will keep in a covered pan 3–4 weeks in freezer.",
    ],
    notes: null,
  },
  {
    id: 77,
    title: "Bavarian Apple Torte",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "450° for 10 minutes, then 400° for 25 minutes",
    ingredients: [
      { amount: "½ c", item: "margarine" },
      { amount: "1/3 c", item: "white sugar (base)" },
      { amount: "1 c", item: "flour" },
      { amount: "¼ tsp", item: "vanilla (base)" },
      { amount: "one 8 oz pkge", item: "cream cheese (soft)" },
      { amount: "¼ c", item: "white sugar (first layer)" },
      { amount: "1", item: "egg (beaten)" },
      { amount: "¼ tsp", item: "vanilla (first layer)" },
      { amount: "4 c", item: "sliced apples" },
      { amount: "1/3 c", item: "white sugar (topping)" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "½ c", item: "slivered almonds" },
    ],
    steps: [
      "To prepare base, cream marg. and sugar. Blend in flour and vanilla. Mix well and press into bottom of 9\" spring form pan or pie plate.",
      "To prepare first layer, cream sugar and cheese. Add egg and vanilla. Blend until smooth and creamy. Pour over base.",
      "To prepare topping, mix sugar and cinnamon, stir in apples. Place on top of first layer, sprinkle with almonds and bake.",
    ],
    notes: null,
  },
  {
    id: 78,
    title: "Brownies",
    contributor: "Lorna",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 25–30 minutes",
    ingredients: [
      { amount: "3/4 c", item: "flour" },
      { amount: "½ tsp", item: "baking powder" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "½ c", item: "butter" },
      { amount: "¼ c", item: "Fry's cocoa" },
      { amount: "3/4 c", item: "white sugar" },
      { amount: "2", item: "eggs" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "3/4 c", item: "chopped nuts" },
    ],
    steps: [
      "Melt butter, stir in cocoa, then sugar, eggs and vanilla.",
      "Beat by hand (ingredients mixed in same pan used for baking).",
      "Add dry ingredients, then nuts. Bake or microwave on high power for 3½–4½ minutes. Turn as required to avoid hot spot.",
      "Ice when cool, if desired.",
    ],
    notes: null,
  },
  {
    id: 79,
    title: "Pineapple Cherry Square",
    contributor: "Fleurette",
    category: "Pies & Desserts",
    servings: null,
    temps: "375° for 30 minutes",
    ingredients: [
      { amount: "1 – 16 oz can", item: "crushed pineapple" },
      { amount: "2", item: "beaten eggs" },
      { amount: "1½ tbsp", item: "cornstarch" },
      { amount: "½ c", item: "sugar" },
      { amount: "1 – 8 oz jar", item: "coarsely chopped maraschino cherries" },
      { amount: "1½ c", item: "flour" },
      { amount: "2 c", item: "oatmeal" },
      { amount: "¼ lb.", item: "margarine or butter (melted)" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "1½ c", item: "brown sugar" },
    ],
    steps: [
      "Stir filling ingredients (pineapple, eggs, cornstarch, sugar, cherries) over a low flame until thick. Allow to cool.",
      "In a bowl sift the crust ingredients (flour, oatmeal, margarine, baking soda, brown sugar) together. Make a crumbly mixture by blending lightly with your fingers.",
      "Spread half of the mixture in a 13 x 9 greased pan.",
      "Spread the pineapple-cherry mixture over the crumbs and cover with the rest of the crumb mixture.",
      "Bake until lightly brown. Allow time to cool and cut in squares.",
    ],
    notes: "May be served plain, with whipped cream, or with cherry or vanilla ice cream.",
  },
  {
    id: 80,
    title: "Nanaimo Bars",
    contributor: "Lorna",
    category: "Pies & Desserts",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "½ c", item: "butter" },
      { amount: "1", item: "egg" },
      { amount: "1 c", item: "coconut (fine)" },
      { amount: "¼ c", item: "sugar" },
      { amount: "5 tbsp", item: "cocoa" },
      { amount: "2 c", item: "graham cracker crumbs" },
      { amount: "½ c", item: "chopped walnuts" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "¼ c", item: "butter (custard icing)" },
      { amount: "2 tbsp", item: "custard powder (vanilla)" },
      { amount: "3 tbsp", item: "milk" },
      { amount: "2 c", item: "icing sugar" },
      { amount: "4 squares", item: "semi sweet chocolate" },
      { amount: "1 tbsp", item: "butter (for chocolate topping)" },
    ],
    steps: [
      "Place softened butter in bowl, add sugar, cocoa, vanilla & egg. Set bowl over pan of boiling water.",
      "Stir until butter has melted and mixture resembles custard. Combine cracker crumbs, coconut and nuts.",
      "Blend well and add to custard mixture. Pack in 9\" square pan and spread with custard icing.",
      "Mix custard icing ingredients (¼ c butter, custard powder, milk, icing sugar) and pour over base layer. Let set 15 minutes.",
      "Melt 4 squares semi sweet chocolate with 1 tbsp butter and spread on custard icing. Cool and cut.",
    ],
    notes: null,
  },
  {
    id: 81,
    title: "Buttertart Bars",
    contributor: "Fleurette",
    category: "Pies & Desserts",
    servings: null,
    temps: "350° for 15 minutes (crust), then 20 minutes (filling)",
    ingredients: [
      { amount: "½ c", item: "margarine" },
      { amount: "2 tbsp", item: "brown sugar" },
      { amount: "1 c", item: "flour" },
      { amount: "2", item: "beaten eggs" },
      { amount: "½ c", item: "oatmeal" },
      { amount: "½ tsp", item: "baking powder" },
      { amount: "½ c", item: "chopped nuts" },
      { amount: "1½ c", item: "brown sugar" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "1 tsp", item: "vanilla" },
    ],
    steps: [
      "Cut flour and brown sugar into margarine until mixture is crumbly. Press into buttered 9 inch square pan. Bake.",
      "Beat eggs well and add remaining filling ingredients. Pour over partially baked crumb layer and bake 20 minutes. Cool and cut.",
    ],
    notes: null,
  },
  {
    id: 82,
    title: "Butterscotch Squares",
    contributor: "Karen",
    category: "Pies & Desserts",
    servings: null,
    temps: "Refrigerate 3 hours",
    ingredients: [
      { amount: "to cover pan", item: "whole graham wafers" },
      { amount: "1", item: "egg (beaten)" },
      { amount: "1 c", item: "margarine" },
      { amount: "1 c", item: "brown sugar" },
      { amount: "½ c", item: "milk" },
      { amount: "1 c", item: "coconut" },
      { amount: "1 c", item: "graham wafer crumbs" },
      { amount: "½ c", item: "walnuts (chopped)" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "3 c", item: "icing sugar" },
      { amount: "¼ c", item: "melted margarine" },
      { amount: "5 tbsp", item: "cocoa" },
      { amount: "3 tbsp", item: "boiling water" },
    ],
    steps: [
      "Line the bottom of a 9 X 12 pan with whole graham wafers.",
      "To prepare filling, bring to a boil margarine, brown sugar, milk and egg. Boil for about 3–4 minutes. Set aside to cool. When cool, add coconut, graham wafer crumbs, walnuts and vanilla. Pour this over the graham wafers and spread evenly.",
      "To prepare icing, mix icing sugar and cocoa. Blend in the melted margarine and boiling water, beating with an electric beater until creamy and smooth. You may need to add a little more boiling water to make the icing a bit on the runny side. Ice the squares. Refrigerate.",
    ],
    notes: null,
  },
  {
    id: 83,
    title: "Panocha (Fudge)",
    contributor: "Lorna",
    category: "Pies & Desserts",
    servings: null,
    temps: "Cook to 238° (soft ball stage)",
    ingredients: [
      { amount: "1½ c", item: "granulated sugar" },
      { amount: "1/3 c", item: "light cream (evap. milk)" },
      { amount: "1 tsp", item: "vanilla" },
      { amount: "1 c", item: "brown sugar" },
      { amount: "1/3 c", item: "milk" },
      { amount: "2 tbsp", item: "margarine" },
      { amount: "½ c", item: "broken pecans" },
    ],
    steps: [
      "Butter the sides of a heavy 2 qt. saucepan and in it combine sugars, cream, milk and margarine. Heat over medium heat stirring constantly till sugars dissolve and mixture comes to boiling.",
      "Cook to soft ball stage (238°) – stir only if necessary. Immediately remove from heat and cool to lukewarm (110°) without stirring. Add vanilla.",
      "Beat vigorously till fudge becomes thick and starts to lose its gloss. Quickly stir in nuts and spread in buttered pan. Score while warm. Cut when firm.",
    ],
    notes: null,
  },
  {
    id: 84,
    title: "Sugared Popcorn",
    contributor: "Phyllis",
    category: "Miscellaneous",
    servings: null,
    temps: "Boil 10 minutes",
    ingredients: [
      { amount: "3 tbsp", item: "margarine" },
      { amount: "1½ c", item: "brown sugar" },
      { amount: "1/8 c", item: "water" },
      { amount: "approx. 12 c", item: "popcorn" },
    ],
    steps: [
      "Melt margarine in pan.",
      "Add brown sugar and water.",
      "Boil 10 minutes and pour over popcorn. Stir to coat.",
    ],
    notes: null,
  },
  {
    id: 85,
    title: "Caramel Popcorn",
    contributor: "Lorna",
    category: "Miscellaneous",
    servings: null,
    temps: "300° on Candy Thermometer (hard crack stage)",
    ingredients: [
      { amount: "1 c", item: "white sugar" },
      { amount: "1/3 c", item: "brown sugar" },
      { amount: "1 tsp", item: "vinegar" },
      { amount: "¼ c", item: "water" },
      { amount: "½ c", item: "margarine" },
      { amount: "½ c", item: "butter" },
      { amount: "1 tbsp", item: "corn syrup" },
      { amount: "dash", item: "salt" },
      { amount: "4–5 quarts", item: "freshly popped popcorn" },
    ],
    steps: [
      "In heavy saucepan boil to hard crack stage (280–300° on candy thermometer) the first 7 ingredients.",
      "Remove from heat and beat in 1 tsp vanilla.",
      "Pour in a thin stream on popcorn, while stirring quickly to coat all popcorn.",
    ],
    notes: "Tastes like Cracker Jack or Poppycock.",
  },
  {
    id: 86,
    title: "Chocolate Chip Ice Cream Sandwiches",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "to taste", item: "homemade chocolate chip cookies" },
      { amount: "to taste", item: "ice cream" },
    ],
    steps: [
      "When making the chocolate chip cookies, drop by tablespoon and press down, shaping into circles.",
      "Completely cool cookies.",
      "Soften ice cream and spoon on the bottom side of cookie, placing another cookie on top (bottom side down).",
      "Wrap individually in saran wrap and keep in freezer for the kids on hot days.",
    ],
    notes: null,
  },
  {
    id: 87,
    title: "Novel Nuts",
    contributor: "Gail",
    category: "Miscellaneous",
    servings: null,
    temps: "225° for 1 hour",
    ingredients: [
      { amount: "1 lb", item: "large pecan halves" },
      { amount: "1", item: "egg white" },
      { amount: "1 tsp", item: "cold water" },
      { amount: "½ c", item: "sugar" },
      { amount: "¼ tsp", item: "salt" },
      { amount: "½ tsp", item: "cinnamon" },
      { amount: "a sprinkle", item: "ground nutmeg" },
    ],
    steps: [
      "Beat egg white and water until frothy.",
      "Add pecans and mix until well coated.",
      "Combine sugar, salt, cinnamon and nutmeg. Add to the pecan mixture.",
      "Bake 1 hour at 225° on buttered cookie sheet, and be sure to stir mixture every 15 minutes.",
    ],
    notes: null,
  },
  {
    id: 88,
    title: "Bacon & Cheddar Munchies",
    contributor: "Melba",
    category: "Miscellaneous",
    servings: null,
    temps: "400° for 12 minutes (no longer)",
    ingredients: [
      { amount: "1 c", item: "grated cheddar cheese" },
      { amount: "½ c", item: "flour" },
      { amount: "½ tsp", item: "paprika" },
      { amount: "¼ tsp", item: "dry mustard" },
      { amount: "pinch", item: "cayenne" },
      { amount: "¼ c", item: "margarine" },
      { amount: "½ c", item: "rice krispies" },
      { amount: "6 slices", item: "bacon (crisp & crumbled)" },
    ],
    steps: [
      "Mix cheese, flour and seasonings.",
      "Add margarine and mix by hand.",
      "Work in cereal and bacon.",
      "Roll into 1\" balls and place on ungreased cookie sheet.",
      "Bake.",
    ],
    notes: null,
  },
  {
    id: 89,
    title: "Appetizer Stuffed French Loaf",
    contributor: "Fran",
    category: "Miscellaneous",
    servings: null,
    temps: "Refrigerate 3–4 hours before serving",
    ingredients: [
      { amount: "1 long thin", item: "French Stick" },
      { amount: "2 large pkgs.", item: "cream cheese" },
      { amount: "½ lb.", item: "liverwurst" },
      { amount: "¼ c", item: "beer" },
      { amount: "¼ c", item: "sliced radish" },
      { amount: "¼ c", item: "watercress (parsley)" },
      { amount: "¼ c", item: "chopped onion" },
      { amount: "1 tbsp", item: "dry mustard" },
    ],
    steps: [
      "Cut French stick into 3's and pull centre out to form a tube (hollow – diameter about 1½\") for the filling. Toast bread crumbs – this is to be added to the cheese mixture.",
      "Soften the cream cheese and liverwurst.",
      "Add ¼ c beer, radishes, watercress, chopped onions and dry mustard.",
      "Stir in toasted bread crumbs.",
      "Stuff centre of French stick with this mixture and wrap tightly in saran.",
      "Refrigerate 3–4 hours before serving. Slice 1\" thick and serve.",
    ],
    notes: "This is different and always a hit!",
  },
  {
    id: 90,
    title: "Stuffed Mushroom Caps",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: "350° for 18 to 20 minutes",
    ingredients: [
      { amount: "1 lb (approx. 24)", item: "mushrooms" },
      { amount: "1 can (6 oz.)", item: "crab meat" },
      { amount: "1", item: "egg – well beaten" },
      { amount: "¼ c", item: "fine breadcrumbs" },
      { amount: "¼ c", item: "clamato juice" },
      { amount: "1 tsp", item: "lemon juice" },
      { amount: "dash", item: "Worcestershire Sauce" },
      { amount: "2 tsp", item: "finely chopped celery" },
      { amount: "1 tsp", item: "finely chopped onion" },
      { amount: "to taste", item: "salt and pepper" },
      { amount: "¼ c", item: "melted butter" },
      { amount: "2 tsp", item: "finely chopped parsley" },
      { amount: "to taste", item: "crumbled bacon" },
      { amount: "½ c", item: "bread crumbs" },
    ],
    steps: [
      "Wash mushrooms, dry thoroughly. Remove stems for other use.",
      "In a bowl thoroughly combine crabmeat, egg, ¼ c fine breadcrumbs, clamato juice, lemon juice, celery, onion and Worcestershire Sauce. Season with salt and pepper to taste.",
      "Fill mushroom caps with this mixture.",
      "Toss together ½ c breadcrumbs, melted butter, parsley and bacon. Sprinkle this mixture over mushroom caps.",
      "Place caps on baking sheet and bake 350° for 18–20 minutes.",
    ],
    notes: null,
  },
  {
    id: 91,
    title: "Meat Paté",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: "Refrigerate at least 1 hour",
    ingredients: [
      { amount: "1–2", item: "green onions, finely chopped" },
      { amount: "1 pkg", item: "German spread sausage (preferably Braunschweiger or Liverwurst)" },
      { amount: "1/3 lb", item: "butter" },
      { amount: "1 tbsp", item: "cream" },
    ],
    steps: [
      "Mix butter and cream together.",
      "Mix meat and onions together.",
      "Combine butter mixture and meat mixture. Mix well. (This blends best when mixed with your hands.)",
      "Shape into a ball and wrap in saran or handiwrap. Refrigerate at least 1 hour.",
      "Remove from fridge about ½ hour before serving and let stand at room temperature.",
    ],
    notes: null,
  },
  {
    id: 92,
    title: "Antipasta",
    contributor: "Beryl",
    category: "Miscellaneous",
    servings: null,
    temps: "Boil 10 minutes, stand 5 minutes",
    ingredients: [
      { amount: "2 cans", item: "green beans" },
      { amount: "2 lbs", item: "cauliflower" },
      { amount: "2 jars", item: "pickled onions (drained and soaked in cold water)" },
      { amount: "1 – 32 oz. jar", item: "dill pickles" },
      { amount: "2 lbs", item: "red peppers" },
      { amount: "2 lbs", item: "green peppers" },
      { amount: "2 cans", item: "black olives (pitted)" },
      { amount: "1 can", item: "green olives (pitted)" },
      { amount: "4 cans", item: "mushrooms" },
      { amount: "4 cans", item: "tuna" },
      { amount: "1 gallon", item: "ketchup" },
      { amount: "1½ c", item: "mazola oil" },
      { amount: "1½ c", item: "vinegar" },
    ],
    steps: [
      "Finely chop all ingredients.",
      "Mix all ingredients together except tuna and olives.",
      "Boil for 10 minutes.",
      "Add other ingredients and let stand 5 minutes.",
      "Put into jars.",
    ],
    notes: "Yield: 24 pints.",
  },
  {
    id: 93,
    title: "Nachos",
    contributor: "Corinne",
    category: "Miscellaneous",
    servings: null,
    temps: "350° for 15–20 minutes",
    ingredients: [
      { amount: "1 lb bag", item: "Doritos or corn chips" },
      { amount: "1 lb", item: "cheese (cheddar or colby)" },
      { amount: "to taste", item: "Picante sauce or hot taco sauce" },
      { amount: "1", item: "avocado" },
      { amount: "2", item: "tomatoes" },
      { amount: "1 can", item: "bean dip" },
    ],
    steps: [
      "Spread chips on a cookie sheet. Grate cheese and spread over chips.",
      "Cut tomatoes into small cubes and spread over mixture, then mash up avocado and also place it on the mixture along with the bean dip.",
      "Spoon on as much Picante sauce as desired and Bake until cheese is melted.",
    ],
    notes: null,
  },
  {
    id: 94,
    title: "4 Large Cheese Balls",
    contributor: "Lorna",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 c", item: "butter" },
      { amount: "2 or 3 cloves", item: "garlic (crushed)" },
      { amount: "1 dash", item: "tabasco or hot pepper sauce" },
      { amount: "8 oz.", item: "cream cheese" },
      { amount: "7½ oz.", item: "sharp cheddar cheese" },
      { amount: "1¼ oz.", item: "blue cheese" },
      { amount: "6 oz.", item: "canadian cheese slices" },
      { amount: "6 oz.", item: "nippy strong cheese slices" },
      { amount: "1 tsp.", item: "pimento (optional)" },
      { amount: "3 tbsp.", item: "cream" },
    ],
    steps: [
      "In 2 qt. saucepan, melt cheeses, butter, garlic, etc over low heat while stirring constantly.",
      "Remove from heat and cool until slightly hard. Beat with rotary beaters until smooth after adding cream.",
      "Shape into four balls and roll in chopped nuts or garnish with parsley for serving with crackers, etc. Cheeseballs may be frozen and thawed a couple hours before needed.",
    ],
    notes: "Yield: 4 large cheese balls.",
  },
  {
    id: 95,
    title: "Mustard Sauce",
    contributor: "Melba",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "2", item: "eggs" },
      { amount: "1/3 c", item: "sugar" },
      { amount: "¼ c", item: "butter" },
      { amount: "¼ c", item: "mustard" },
      { amount: "½ c", item: "vinegar" },
    ],
    steps: [
      "In double boiler mix sugar and mustard. Add eggs and vinegar, beat well. Add butter and cook, stirring often. If too thick add a little water.",
      "Place the top of the double boiler on the burner and stir constantly. This will keep for a long time.",
    ],
    notes: null,
  },
  {
    id: 96,
    title: "Orange Glaze for Ham",
    contributor: "Cally",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "½ c", item: "brown sugar" },
      { amount: "½ tsp.", item: "dry mustard" },
      { amount: "2 tbsp.", item: "corn starch (heaping)" },
      { amount: "½ c", item: "orange juice (pre-mixed)" },
    ],
    steps: [
      "Combine first three ingredients with ½ to ¾ cups of mixed orange juice.",
      "Cook ham for 1½ hours, drain off fat. Start basting once the fat is drained off. Pour some of the marinade over the ham at 20 minute intervals until all the marinade is used up. During the baking process, baste the ham with the marinade from the bottom of the pan.",
    ],
    notes: null,
  },
  {
    id: 97,
    title: "Sweet & Sour Sauce",
    contributor: "Lorna",
    category: "Miscellaneous",
    servings: null,
    temps: "Simmer 10 minutes",
    ingredients: [
      { amount: "½ c", item: "brown sugar" },
      { amount: "3 tbsp.", item: "cornstarch" },
      { amount: "¼ tsp", item: "dry mustard" },
      { amount: "1/8 tsp.", item: "ginger" },
      { amount: "1 tsp.", item: "salt" },
      { amount: "3/4 tsp.", item: "chili powder" },
      { amount: "1 clove", item: "garlic (crushed)" },
      { amount: "5 tbsp.", item: "vinegar" },
      { amount: "1 c", item: "tomato juice" },
      { amount: "1 c", item: "water" },
    ],
    steps: [
      "Mix brown sugar, cornstarch and seasonings. Add liquids and well crushed garlic. Simmer 10 minutes until thickened, stirring constantly.",
    ],
    notes: "Works well for sauce on country style pork ribs. Brown pork, place in large casserole or roaster, pour sauce over and bake covered in 325° oven approximately 1 hour.",
  },
  {
    id: 98,
    title: "Orange Sauce for Fruit",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "250 g pkg.", item: "cream cheese (8 oz.)" },
      { amount: "½ c", item: "orange juice (pre-mixed)" },
      { amount: "2 tbsp.", item: "sugar" },
      { amount: "1 tsp.", item: "grated orange rind" },
    ],
    steps: [
      "Combine ingredients and use for dip for fruit or over pound cake.",
    ],
    notes: null,
  },
  {
    id: 99,
    title: "Salami",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: "225° for 3 hours",
    ingredients: [
      { amount: "6 lbs", item: "lean ground beef" },
      { amount: "½ c", item: "quick cure salt" },
      { amount: "3 tbsp.", item: "liquid smoke" },
      { amount: "2 tsp.", item: "pepper" },
      { amount: "1 tsp.", item: "garlic powder" },
    ],
    steps: [
      "Mix thoroughly for about 5 minutes by hand. Cover and put in fridge for 24 hours.",
      "Roll into tight rolls and put on broiler pan rack. When finished baking, cool and wrap in tin foil and freeze.",
    ],
    notes: null,
  },
  {
    id: 100,
    title: "Slush",
    contributor: "Lorna",
    category: "Miscellaneous",
    servings: null,
    temps: "Freeze until partially set",
    ingredients: [
      { amount: "2 large pkg.", item: "jello (raspberry)" },
      { amount: "4 c", item: "sugar" },
      { amount: "10 c", item: "water (boiling) + 10 c cold" },
      { amount: "4 qts.", item: "pineapple juice" },
      { amount: "2 c", item: "freshly squeezed lemon juice" },
      { amount: "2 tsp.", item: "almond extract" },
      { amount: "8 qts.", item: "ginger ale or 7-up" },
    ],
    steps: [
      "Bring jello and sugar and water to boil. Remove from heat and add 10 cups cold water, pineapple juice, lemon juice and almond extract.",
      "Freeze in coffee cans which have been lined with plastic bags. Remove before completely frozen. 2 hours before serving, place in a punch bowl and break up a little. Add mixer.",
    ],
    notes: null,
  },
  {
    id: 101,
    title: "Crabmeat Dip",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 can", item: "drained crabmeat" },
      { amount: "½ c", item: "mayonnaise" },
      { amount: "2 tbsp", item: "catsup or chili sauce" },
      { amount: "3 tbsp.", item: "lemon juice" },
      { amount: "to taste", item: "pepper" },
      { amount: "to taste", item: "garlic salt or powder" },
      { amount: "½ tsp.", item: "horseradish" },
    ],
    steps: [
      "Combine all ingredients and mix well.",
    ],
    notes: null,
  },
  {
    id: 102,
    title: "Vegetable Dip",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "1 c", item: "mayonnaise" },
      { amount: "1 tsp.", item: "curry powder" },
      { amount: "1 tsp.", item: "mustard (not dry)" },
      { amount: "1 tsp.", item: "onion salt" },
      { amount: "1 tsp.", item: "angastura (spice)" },
      { amount: "½ tsp.", item: "paprika" },
    ],
    steps: [
      "Combine all ingredients and mix well.",
    ],
    notes: null,
  },
  {
    id: 103,
    title: "Icicle Pickles",
    contributor: "Karen",
    category: "Miscellaneous",
    servings: null,
    temps: null,
    ingredients: [
      { amount: "6 medium", item: "cucumbers, peeled" },
      { amount: "1", item: "green pepper cut in strips" },
      { amount: "1", item: "red pepper cut in strips" },
      { amount: "½ c", item: "course pickling salt" },
      { amount: "2 c", item: "vinegar" },
      { amount: "3", item: "onions, thinly sliced" },
      { amount: "2 c", item: "granulated sugar" },
      { amount: "2 tsp", item: "celery seed" },
      { amount: "2 tsp", item: "mustard seed" },
      { amount: "½ tsp", item: "turmeric" },
    ],
    steps: [
      "Cut cucumbers into long strips, removing most of seeds. Combine in large bowl with onions, peppers and salt. Soak in ice water for 3 hours, adding more ice as it melts. Drain well.",
      "In large saucepan combine remaining ingredients. Bring to a boil and simmer 5 minutes. Add vegetables and return to boil.",
      "Pack into hot sterilized jars, covering vegetables with liquid. Seal.",
    ],
    notes: "Yield: 3 pints.",
  },
  {
    id: 104,
    title: "Magic Cookie Bars",
    contributor: "Michelle (2012)",
    category: "Miscellaneous",
    servings: null,
    temps: "350° for 30 minutes",
    ingredients: [
      { amount: "½ c", item: "butter or margarine – melted" },
      { amount: "1 cup", item: "graham cracker crumbs" },
      { amount: "6 oz", item: "chocolate chips" },
      { amount: "6 oz", item: "butterscotch chips" },
      { amount: "1 c", item: "coconut" },
      { amount: "1 c", item: "chopped walnuts" },
      { amount: "1 can", item: "sweetened condensed milk" },
    ],
    steps: [
      "Layer from top to bottom of recipe in 8 x 8 pan.",
      "Bake at 350° for 30 minutes.",
    ],
    notes: null,
  },
];
